language: java
jdk:
  - openjdk8
  - openjdk11



script:
  - "./test.sh"
  - "ant test"
  - "ant jar"

# Workaround for https://github.com/travis-ci/travis-ci/issues/7706
addons:
  apt:
    packages:
      - ant-optional 
